### ISSUE TITLE
Npm repo url not good

### ISSUE THREAD

**Issue by alcaidio** [ngxpert/hot-toast#14]
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[x] Other... Please describe:
</code></pre>

Just to inform repository url is not good in npm 
https://www.npmjs.com/package/@ngneat/hot-toast

**Comment by shhdharmen** [comment]
Not sure where did you check. But it's correct on NPM.

**Comment by alcaidio** [comment]
nope the repository url on the right side

**Comment by daboudii** [comment]
I don't now what happened but the repo went from [@ngneat/hot-toast](https://www.npmjs.com/package/@ngneat/hot-toast) to [@ngxpert/hot-toast](https://www.npmjs.com/package/@ngxpert/hot-toast) 

It would have been nice to warn user about this change, is it still Netanel Basal behind @ngxpert ?

**Comment by shhdharmen** [comment]
nope, I manage ngxpert org.
