### ISSUE TITLE
Bug install on Angular 18

### ISSUE THREAD

**Issue by avmesquita** [ngxpert/hot-toast#19]
## I'm submitting a bug install on Angular 18

<pre>
<code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code>
</pre>

## Current behavior

Installing on Angular 18, apear like:

At visual code, apear like:
![image](https://github.com/user-attachments/assets/3eea9be9-d609-4cd1-8384-80f09b977bc3)

At console, apear like:
![image](https://github.com/user-attachments/assets/3c09e41f-ebfb-454a-ad2e-9a02f8164ad2)

package.json:
```
{
     "@angular/core": "^18.1.0"
...
    "@ngneat/overview": "^6.0.0",
    "@ngxpert/hot-toast": "^3.0.1",
...
}
```

## Expected behavior
Success.

## Minimal reproduction of the problem with instructions

Minimal installing as standalone component.

## What is the motivation / use case for changing the behavior?

Use component.

## Environment

<pre><code>
Angular version: 18.1.0

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: 18.19.0
- Platform:  Windows

Others:
</code></pre>

**Comment by shhdharmen** [comment]
You need to import provider in app config, [link](https://github.com/ngxpert/hot-toast?tab=readme-ov-file#standalone-setup).
