### ISSUE TITLE
Angular Route Transition Animation affects Toasts too (Visual Bug)

### ISSUE THREAD

**Issue by 0x426** [ngxpert/hot-toast#40]
First of all, thank you for the awesome library, really neat.

# Environment
* Tested on Chrome (desktop) version 131.0.6778.109
* Angular v19
* @ngneat/overview 6.1.1
* @ngxpert/hot-toast 4.1.1

# Stackblitz example:
* https://stackblitz.com/edit/stackblitz-starters-hgxznsca?file=src%2Fmain.ts

# Current Behavior
If using the Angulars [Route Transition Animation](https://angular.dev/guide/animations/route-animations) on a router(outlet), in the Stackblitz example simplified with a counter, the Toasts / Toast Container gets animated too, even if it's DOM elements are not hierarchical nested within the router.

<img width="1512" alt="toast-01" src="https://github.com/user-attachments/assets/bf59d5e0-bcd7-4aa3-8527-a4a02a34226f" />

I've already tried to apply different styles on the toast container (z-index, various positions, etc.) but nothing seems to work. For the Stackblitz example I made the animation really slow (1s).

# Reproduce
1. Open the Stackblitz example, a "Hello world" Toast will open in the bottom right corner.
2. Hit "Increment" and you can see, how the Route Transition affects the toast container / toasts.
3. Hit "Make me a Toast" and you'll see the usual animation as expected.

You can play with the Route Transition Animation in the global css file.

# Expected Behavior
The toast container / the toasts should not be affected by the Route Transition Animation.

# Misc
I'm not 100% sure if it's a Hot Toast Issue, or more a Angular one, with Route Transition Animations which elements get animated when routing (f. e. all child components loaded in a component, which performs routing).

https://github.com/user-attachments/assets/21a79263-b24b-49f4-b8cb-e0420f12e5e9

**Comment by shhdharmen** [comment]
It's neither hot-toast issue nor angular route, it's how view-transitions work. You need to skip view-transition for hot-toast. As view-transitions are still in developer preview and not support fully supported I recommend not to use it much.

Demo: https://stackblitz.com/edit/stackblitz-starters-kdi9yzn7?file=src%2Fglobal_styles.css
