### ISSUE TITLE
[HOT_TOAST] Specs: Write cypress tests for missing features

### ISSUE THREAD

**Issue by shhdharmen** [ngxpert/hot-toast#7]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[x] Other... Please describe:
</code></pre>

## Current behavior

Cypress tests are not written for all cases.

## Expected behavior

Library should have test cases written for all cases.

## What is the motivation / use case for changing the behavior?

To keep the library bug free.

**Comment by coljacarls** [comment]
Maybe I can help you with Cypress. Still need help?

**Comment by shhdharmen** [comment]
Yes
